### PR TITLE
Configure which combination of delimiters to use

### PR DESCRIPTION
**Pull request by ibraimgm**
Rebased changes of #12 .
Please take a look at the discussion on #16

### CODE REVIEW

**Comment by peregrinogris** [comment]
I'll check out this patch, but yesterday I tried a similar approach and the rendering got quite slow.

**Comment by runexec** [comment]
Any updates on this by chance?

**Comment by jrattray13** [comment]
Seems to work better, let me know if there are any issues. Sorry for delay.

**Comment by runexec** [comment]
No problem. Trying it out now. Thanks for everything.

**Pull request merged**
