### PR TITLE
Added more options to color syntax

### PR DESCRIPTION
**Pull request by ibraimgm**
Added a 'Square Brackets' and 'All' (brackets, square brackets and
parenthesis) option on 'Settings'.
Requested by issue #11

### CODE REVIEW

**Comment by alexchandel** [comment]
@ibraimgm Could you please change this to instead add checkboxes for "Parentheses", "Brackets", and "Braces"? Also this needs a git rebase.

**Comment by alexchandel** [comment]
@ibraimgm Could you please rebase this?

**Comment by ibraimgm** [comment]
@alexchandel, working on it, please take a look at #16. If it's acceptable, I can send a new pull request.

**Comment by peregrinogris** [comment]
Any chance to get this merged/reviewed? :)

**Comment by alexchandel** [comment]
@ibraimgm Well as of now, Parens are supported, but there's no ability to specify (via checkboxes) which combination you want.

**Comment by peregrinogris** [comment]
Besides the last comment from @alexchandel, the swackets-view.cofee file changed a good deal and this patch no longer makes sense. The way open/close syntax is checked was optimized to check for a single char at a time.
@ibraimgm it's probably easier to close this PR and start over I'm afraid.

**Comment by ibraimgm** [comment]
For those interested, please take a look at #19

**Pull request closed without merging**
