### PR TITLE
Refactor for big speed improvements

### PR DESCRIPTION
**Pull request by rogeriochaves**
Hello,

So, I loved swackets, but it is very slow, leading me to often have to disable it to use atom.
Then I thought of different ways of colouring the elements, first idea was this one:

https://jsfiddle.net/ty6uhmy1/1/

Instead of making a lot of calls to the DOM, which is slow, I'd just replace all of it at once. But this doesn't work in atom, because it tracks those dom nodes, if we replace them, the editor pane freezes.

So, I had to still iterate through each DOM element and mutate them, but with the help of [letitalew ideas](http://blog.letitialew.com/post/30425074101/repaints-and-reflows-manipulating-the-dom), I did somethings to make it as efficient as possible:

- Hide the `.lines` element with `display = 'none'` and unhide it after changing all the other elements, this way we will only have one repaint
- Add CSS classes instead of inline styles, this is much faster
- Removed jQuery, it's unecesary and slow
- Now there's only a single loop in the code
- It uses regexes to try to match text instead of iterating child elements or something

Here's a jsfiddle with those ideas:

https://jsfiddle.net/ty6uhmy1/3/

I haven't done any benchmarks, but it looks much faster for me as I code, I don't have to disable it anymore.

But there is still a problem, the colors are now on the stylesheet, so how can we make it configurable?

By the way, I stole the colors from the [lighttable rainbow plugin](https://github.com/LightTable/Rainbow), I don't know if there is a default color pallete for those plugins across code editors, but I believe there should be.

captura de tela 2015-12-14 as 00 26 37

I didn't understood that part of the code about range, point or scroll positions, so I deleted it. It's fast enough so if that was there for performance it might not be needed anymore.

Please let me know if I missed anything!

--- Edit ---

Fixed coloring when having immediate closed parens, like in `something()`

### CODE REVIEW

**Comment by dkniffin** [comment]
:+1: I just installed swackets and love it, but it was horribly slow. I've just installed this fork of the plugin, and I'll be working on some clojure for a while. I'll report back any slowness.

**Comment by jrattray13** [comment]
Thanks for this, the code that remains does seem slightly faster which is always good :+1: 

However, the code you removed (range/point section) was there so it could get the depth of nesting already, since if you're on line 90 of a file, you can't just start from the swackets-0 css, as when you scroll up the colors will change due to the original nesting changing, so that code goes through the pre-buffer code (so lines 1-89) to get the current nesting level (i.e. swackets-3) so it is correct and all brackets match no matter if you scroll/change buffer. But apart from that it is fine (not sure on the colors though). I will merge it in on the weekend (if it stays fast with existing code added in).

Thanks.

**Comment by dkniffin** [comment]
I did notice the colors change. It might be a good idea to add that code back in. Other than that, I haven't seen any problems.

**Comment by rogeriochaves** [comment]
@jrattray13 I'll try to add this prebuffer again into the code, but could you describe better some points?

- Whats this first-second line thing?
- How does those zIndexes work?
- Whats this #Atom bug with DOM?

Just to clarify, basically you calculate in which point should we start the sweatiness count and start applying from there right?

**Comment by jrattray13** [comment]
Correct :+1: 

The first-second line thing is a DOM 'bug' with Atom, basically we (probably not the best way) use the z-index to determine which line is at the top of the buffer (if you can think of a better way please do) because the DOM .lines is abit weird in ordering the lines but we obviously want the lowest number visible so z-index happens to be that group. The first-second line complicates it slightly as occasionally there is a random .lines in the dom (phantom line in the buffer) so we check its not there by verifing if there are two lines in the .lines element (normal not the phantom line). 

See this screengrab for more info:

http://i.snag.gy/tT5Fi.jpg

clearly line 227 is not in the visible buffer and is a weird side effect of scrolling, so in some cases we can accidently select it (if it's z-index is biggest -not in this case) thinking it's the 'first line' in the buffer (so we know where to stop with our calculation of sweatiness count :)

Hope that's enough context, annoying we have to do this stuff (pre calculate) and a shame there is no official Atom API to decorate text color :(

**Comment by rogeriochaves** [comment]
@jrattray13 Thank you for the explanations, helped a lot. I re-added code to precalculate the first parens color on the screen, reordered line groups based on z-index, and workaround to ignore this single line bug.

I've also splitted the code into smaller functions

Now the only thing missing is a way to stylize rainbow colors based on user configuration

**Comment by rogeriochaves** [comment]
Done! Now the colors are configurable from the package settings!

I've also removed the alternate colors, IMO adding more colors in same nested levels it only makes it more confusing, but feel free to reintroduce that idea if you will

**Comment by jrattray13** [comment]
Thanks i'll check it out tomorrow morning, sounds promising :) Thanks for help, appreicated.

**Comment by dkniffin** [comment]
Is this ready to merge in yet? I've been using it for a few weeks now, with no problems.

**Comment by dkniffin** [comment]
I've been using it for a few weeks. The only problem I've seen is this:

If I have two opening parens, with no keyword in the middle (eg `((:foo bar) meh)`), the parens matching gets thrown off. It matches the one after bar, with the first one.

**Comment by dkniffin** [comment]
@jrattray13 any chance of merging this soon?

**Comment by jrattray13** [comment]
Hi yes sorry for late reply, i've actually changed projects at work which lead me to change IDE so I no longer use Atom (and have been really busy) to inspect the changes/pull it in, but hopefully i'll get around to it soon sorry.

**Comment by jrattray13** [comment]
So merged it in, but pulled in existing default colors (feel free to use your own though).

Does appear to be slightly more responsive and colors loop around which is nice. I did remove the alternating colours those, more distracting and harder to get 'right' colors to feel inituitive, maybe I will add functionality back in later.

**Comment by rogeriochaves** [comment]
@jrattray13 awesome :+1:

**Pull request merged**
